name: Build docs

on: [push]

jobs:
    build-docs:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip docs]')"
        steps:
            - uses: actions/checkout@v2
            - run: npm ci
            - run: npm run build
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
